# -*- coding: utf-8 -*-
"""doujin_scrap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QcACulUlucPhdaFs-wm8XlTTaaB4heAX
"""

#画像とタイトルとサークルを取得する
#http://doujinantena.com/list.php?category=update
#上記のURLを取得する
#----------ここから-------------------------
#divタグのclass=listtype-aを取得する
#次のページのリンクも取得
#欲しい情報ごとに分類する（画像 タイトル サークル） imgタグのsrc class="booktitle"  class="circle"
#上記の3つのタグの情報を取得する
#----------ここまで-------------------------
#画像については要調査
#1ページを終えたら次のページ
#ページ遷移がなくなるまで繰り返す
#3つの情報をexcelに書き込む
#毎日AM1:00に実行する
from bs4 import BeautifulSoup
import requests
import openpyxl as px
import time
from urllib.parse import urljoin
import numpy as np

#ページ遷移が終わるまでタイトルと画像とサークル名を取得する
def getScrapList():
  #取得するリストを用意
  img_list = []
  title_list = []
  circle_list = []
  
  #ベースになるアドレス
  base_url = "http://doujinantena.com/"
  dynamic_url = "http://doujinantena.com/list.php?category=update" #初期URL
  
  while True:
    
    #指定したURLのhtmlを取得する
    res = requests.get(dynamic_url)
    res.raise_for_status() # エラー処理
    html = BeautifulSoup(res.content,"html.parser")
    
    #次のページのURLを取得する
    next_page = html.find(class_="nex")
  
    #divタグのclass=listtype-aタグ内のliタグを取得する
    tag_li_list = html.select('.listtype-a > ul > li')
  
 
 
    #取得したタグから3つの情報をリストに格納する
    for li in tag_li_list:
    
      #img srcタグのurlをリストに格納
      tmp = li.find('img')
      img_list.append(tmp['src'])
    
      #titleをリストに格納
      tmp = li.find(class_="booktitle")
      title_list.append(tmp.string)
    
      #circleをリストに格納
      tmp = li.find(class_="circle")
      #get_text()でタグ内のテキストを抜き出す、邪魔なサークル：をreplace()で削除
      circle_list.append(tmp.get_text().replace("サークル：",""))
    
    #次のページのアドレスがない場合終了する
    if bool(next_page) == False:
      break
    
    dynamic_url = urljoin(base_url, next_page.a.get("href"))
    time.sleep(5)
  #print(next_page)
  print("読み込み完了")
  return img_list,title_list,circle_list  

#３つの配列を行列に変換
def reshape_array(img_list,title_list,circle_list):
  np_img = np.array(img_list)
  np_title = np.array(title_list)
  np_circle = np.array(circle_list)
  
  np_list = np.hstack((np_img.reshape(len(np_img),1),np_title.reshape(len(np_title),1),np_circle.reshape(len(np_circle),1)))
  print("変換完了")
  list = np_list.tolist()
  return list

#画像とタイトルとサークル名をexcelに記載する
def write_excel(list,path):
  
    wb = px.Workbook()
    wb.save(path)
    ws = wb.active
    
    colum_head = ["画像","タイトル","サークル名"]
    rows = []
    rows.append(colum_head)
    rows.append(list)
    
    #全行分
    for row in rows:
      ws.append(row)
        
    
    print("ファイル作成完了")
    
[img,title,circle] = getScrapList()
list = reshape_array(img,title,circle)
write_excel(list,"C:\work\python\20190301_scrap_practice\doujin_result.xlsx")

